services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - teranode-network
    user: "${USER_ID}:${GROUP_ID}"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: really_strong_password_change_me
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ${DATA_PATH}/postgres:/var/lib/postgresql/data
    restart: on-failure
    depends_on:
      - data-init
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka-shared:
    container_name: kafka-shared
    image: redpandadata/redpanda:latest
    mem_limit: 1024m
    restart: on-failure
    networks:
      - teranode-network
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://kafka-shared:9092
      - --pandaproxy-addr 0.0.0.0:9093
      - --advertise-pandaproxy-addr localhost:9093
    ports:
      - 8081
      - 9092:9092
      - 9093:9093

  # kafka-console-shared:
  #   container_name: kafka-console-shared
  #   image: docker.redpanda.com/redpandadata/console:latest
  #   networks:
  #     - teranode-network
  #   restart: on-failure
  #   entrypoint: /bin/sh
  #   command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
  #   environment:
  #     CONFIG_FILEPATH: /tmp/config.yml
  #     CONSOLE_CONFIG_FILE: |
  #       kafka:
  #         brokers: ["kafka-shared:9092"]
  #         schemaRegistry:
  #           enabled: true
  #           urls: ["http://kafka-shared:8081"]
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - kafka-shared

  # Aerospike Community Edition
  aerospike:
    container_name: aerospike
    image: aerospike/aerospike-server:8.1
    command: --config-file /etc/aerospike.conf
    networks:
      - teranode-network
    user: "${USER_ID}:${GROUP_ID}"
    ports:
      - 3000:3000
    expose:
      - 3000
      - 3001
      - 3002
    restart: unless-stopped
    volumes:
      - ./aerospike.conf:/etc/aerospike.conf
      - ${DATA_PATH}/aerospike/data:/opt/aerospike/data
      - ${DATA_PATH}/aerospike/smd:/opt/aerospike/smd
    privileged: true  # Allow the container to access raw devices
    hostname: aerospike
    depends_on:
      - data-init

  # Aerospike Enterprise Edition
  aerospike-ee:
    container_name: aerospike
    image: aerospike/aerospike-server-enterprise:8.1
    networks:
      - teranode-network
    user: "${USER_ID}:${GROUP_ID}"
    ports:
      - 3000:3000
    expose:
      - 3000
      - 3001
      - 3002
    restart: unless-stopped
    stop_grace_period: 600s # to allow ASMT to backup the indexes for warm restarts
    volumes:
      - ./aerospike-ee.conf:/etc/aerospike.conf
      - ./aerospike-asmt-wrapper.sh:/aerospike-asmt-wrapper.sh:ro
      - ${DATA_PATH}/aerospike/data:/opt/aerospike/data
      - ${DATA_PATH}/aerospike/smd:/opt/aerospike/smd
      - ${DATA_PATH}/aerospike/asmt:/backup/indexes
    entrypoint: ["/bin/bash", "/aerospike-asmt-wrapper.sh"]
    privileged: true  # Allow the container to access raw devices
    hostname: aerospike
    depends_on:
      - data-init

  # Aerospike exporter for the primary node
  aerospike-exporter:
    image: aerospike/aerospike-prometheus-exporter:latest
    container_name: aerospike-exporter
    environment:
      AS_HOST: aerospike
      AS_PORT: 3000
      AGENT_BIND_PORT: 10145
      METRIC_LABELS: "type='development',source='aerospike'"
    networks:
      - teranode-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.44.0
    ports:
      - 9090:9090
    networks:
      - teranode-network
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ${DATA_PATH}/prometheus:/prometheus
    depends_on:
      - data-init

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3005:3000
    networks:
      - teranode-network
    user: "${USER_ID}:${GROUP_ID}"
    volumes:
      - ./grafana_datasource.yaml:/etc/grafana/provisioning/datasources/main.yaml
      - ./grafana_dashboards/main.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana_dashboards:/var/lib/grafana/dashboards
      - ${DATA_PATH}/grafana/grafana.db:/var/lib/grafana
    depends_on:
      - prometheus
      - data-init

  asset-cache:
    container_name: asset-cache
    image: nginx:1.27.4
    networks:
      - teranode-network
    ports:
      - 8000:8000
    depends_on:
      - asset
    volumes:
      - ./asset-cache-nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx-cache:/tmp/nginx
    restart: on-failure
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 5s
      timeout: 5s
      retries: 5
