{
 "title": "Teranode Service Overview",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "grouping_interval",
    "label": "Grouping Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(propagation_transactions_size_sum,instance)"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "srvc", "label": "Service", "query": { "query": "label_values(service)" } },
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   { "name": "subsystem", "label": "Subsystem", "query": { "query": "label_values(subsystem)" } }
  ]
 },
 "panels": [
  {
   "title": "Processed Transaction by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(increase(teranode_propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,namespace) >0) / 60",
     "legendFormat": "Propagation - {{namespace}}"
    },
    {
     "expr": "sum(increase(teranode_tx_blaster_processed_transactions{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by(namespace,) / 60",
     "legendFormat": "Tx Blaster - {{ namespace }}"
    },
    {
     "expr": "sum(increase(teranode_blockassembly_add_tx_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval]))  by (container,namespace) / 60",
     "legendFormat": "Blockassembly - {{namespace}}"
    }
   ]
  },
  {
   "title": "TX Blaster Generated Transaction",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_blaster_workers{service=~\"tx-blaster-service.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"})",
     "legendFormat": "workers"
    },
    {
     "expr": "sum(increase(teranode_tx_blaster_processed_transactions{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (instance,namespace) / 60 > 0",
     "legendFormat": "Valid-{{instance}}-{{namespace}}"
    },
    {
     "expr": "sum(increase(teranode_tx_blaster_invalid_transactions{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (instance,namespace) / 60 > 0",
     "legendFormat": "Invalid-{{instance}}-{{namespace}}"
    },
    {
     "expr": "sum(increase(teranode_tx_blaster_retry_transactions{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (instance,namespace) / 60 > 0",
     "legendFormat": "Retries-{{instance}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Propagation Processed Transaction per Instance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(increase(teranode_propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (instance,) >0) / 60",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "(sum(increase(teranode_propagation_invalid_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (instance,) >0) / 60",
     "legendFormat": "Invalid: {{instance}}"
    }
   ]
  },
  {
   "title": "Propagation Processed Transaction per node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(increase(teranode_propagation_transactions_count{instance=~\"$instance\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (namespace,) >0) / 60",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(go_goroutines) by (namespace,service)",
     "legendFormat": "{{namespace}}: {{container}}"
    }
   ]
  },
  {
   "title": "Transactions Added by Block Assembly /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_blockassembly_add_tx_count{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,namespace) / 60",
     "legendFormat": "Transactions-{{container}}-{{namespace}}"
    },
    {
     "expr": "sum(teranode_subtreeprocessor_dynamic_subtree_size{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container,namespace)",
     "legendFormat": "Subtree-Size-{{container}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Transactions In Block Assembly",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(sum(teranode_blockassembly_transactions{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container,namespace) >0)",
     "legendFormat": "Transactions-{{namespace}}"
    },
    {
     "expr": "(sum(teranode_blockassembly_queued_transactions{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container,namespace) >0)",
     "legendFormat": "Queued-{{namespace}}"
    },
    {
     "expr": "\n(sum(teranode_blockassembly_subtrees{instance=~\"$instance\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container,namespace) >0) / 60",
     "legendFormat": "Subtrees-{{namespace}}"
    }
   ]
  },
  {
   "title": "Transactions Added to Kafka /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_validator_send_to_block_assembly_count{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,namespace) / 60 > 0",
     "legendFormat": "Tx Data (block assembly)-{{namespace}}"
    },
    {
     "expr": "sum(increase(teranode_validator_send_to_blockvalidation_kafka_count{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,namespace) / 60 > 0",
     "legendFormat": "Tx Meta (block/subtree validation)-{{namespace}}"
    }
   ]
  },
  {
   "title": "Tx Meta read from Kafka /second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreevalidation_set_tx_meta_cache_kafka_count{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,instance) / 60 > 0",
     "legendFormat": "{{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Blaster workers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_blaster_workers{namespace=~\"$namespace\"})by (instance,)   >0",
     "legendFormat": "Workers-{{instance}}"
    },
    {
     "expr": "sum(teranode_tx_blaster_worker_errors{namespace=~\"$namespace\"}) by (instance,)  >0",
     "legendFormat": "Worker errors - {{instance}}"
    }
   ]
  },
  {
   "title": "Queued Blocks in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_block_found_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container,namespace)",
     "legendFormat": "Blocks queued-{{container}}-{{namespace}}"
    },
    {
     "expr": "sum(teranode_blockvalidation_catchup_count{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container,namespace)",
     "legendFormat": "Blocks catchup-{{container}}-{{namespace}}"
    }
   ]
  },
  {
   "title": "Subtrees processed by Subtree Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_subtreevalidation_validate_subtree_count{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container) / 60",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Size of Catchup Channel in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_catchup_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container)",
     "legendFormat": "Blocks catchup-{{container}}"
    }
   ]
  },
  {
   "title": "Subtrees processed",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(teranode_subtreevalidation_validate_subtree_count{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container) >0",
     "legendFormat": "Count: {{container}}"
    },
    {
     "expr": "sum(teranode_subtreevalidation_validate_subtree_duration_sum{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container) >0",
     "legendFormat": "Duration: {{container}}"
    }
   ]
  },
  {
   "title": "Block Chain Mined Block",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "sum(increase(teranode_blockchain_add_block_count{service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[1m])) by (container) >0",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Aerospike UTXO",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_aerospike_utxo_create_batch_count[$grouping_interval])) / 60",
     "legendFormat": "UTXO: Batch Create"
    },
    {
     "expr": "sum(increase(teranode_aerospike_utxo_store[$grouping_interval])) / 60",
     "legendFormat": "UTXO: Store"
    },
    {
     "expr": "sum(increase(teranode_aerospike_utxo_spend_batch_count[$grouping_interval])) / 60",
     "legendFormat": "UTXO: Spend Batch"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_utxo_reset[$grouping_interval])) / 60",
     "legendFormat": "Map: Restore"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_utxo_spend[$grouping_interval])) / 60",
     "legendFormat": "Map: Spend"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_utxo_respend[$grouping_interval])) / 60",
     "legendFormat": "Map: Respend"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_utxo_reset[$grouping_interval])) / 60",
     "legendFormat": "Map: Reset"
    }
   ]
  },
  {
   "title": "Aerospike Tx Meta",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_get[$grouping_interval])) / 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_set_mined[$grouping_interval]))/ 60",
     "legendFormat": "Set"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_delete[$grouping_interval]))/ 60",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_set_mined[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_set_mined_batch[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-Batch"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_set_mined_batch_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-BatchN"
    },
    {
     "expr": "sum(increase(teranode_aerospike_txmeta_get_multi_n[$grouping_interval]))/ 60",
     "legendFormat": "Get-Multi-BatchN"
    },
    {
     "expr": "sum(increase(teranode_aerospike_txmeta_set_mined_batch_err_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Multi-ErrN"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_set_mined_batch[$grouping_interval]))/ 60",
     "legendFormat": "Set-Batch"
    },
    {
     "expr": "sum(increase(teranode_aerospike_map_txmeta_get_multi[$grouping_interval])) / 60",
     "legendFormat": "Get-Multi"
    }
   ]
  },
  {
   "title": "Aerospike MAP UTXO",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_aerospike_utxo_get[$grouping_interval])) / 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_store[$grouping_interval])) / 60",
     "legendFormat": "Store"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_store_spent[$grouping_interval])) / 60",
     "legendFormat": "Spent"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_restore[$grouping_interval])) / 60",
     "legendFormat": "Restore"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_spend[$grouping_interval])) / 60",
     "legendFormat": "Spend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_respend[$grouping_interval])) / 60",
     "legendFormat": "Respend"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_spend_spent[$grouping_interval])) / 60",
     "legendFormat": "Spend Spent"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_reset[$grouping_interval])) / 60",
     "legendFormat": "Reset"
    }
   ]
  },
  {
   "title": "Aerospike MAP Tx Meta",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_aerospike_txmeta_get[$grouping_interval])) / 60",
     "legendFormat": "Get"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_store[$grouping_interval]))/ 60",
     "legendFormat": "Set"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_delete[$grouping_interval]))/ 60",
     "legendFormat": "Delete"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-Batch"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Mined-BatchN"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_get_multi_n[$grouping_interval]))/ 60",
     "legendFormat": "Get-Multi-BatchN"
    },
    {
     "expr": "sum(increase(aerospike_map_txmeta_set_mined_batch_err_n[$grouping_interval]))/ 60",
     "legendFormat": "Set-Multi-ErrN"
    },
    {
     "expr": "sum(increase(aerospike_map_utxo_respend[$grouping_interval]))/ 60",
     "legendFormat": "Respends"
    }
   ]
  },
  {
   "title": "Tx Meta Cache in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_tx_meta_cache_insertions{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,instance) > 0 / 60",
     "legendFormat": "Cache insertions - {{container}} - {{instance}}"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_hits{service!~\"tx-blaster.*\",service=~\"$srvc\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,instance) > 0 / 60",
     "legendFormat": "Cache hits - {{container}} - {{instance}}"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_misses{service!~\"tx-blaster.*\",service=~\"$srvc\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,instance) > 0 / 60",
     "legendFormat": "Cache misses - {{container}} - {{instance}}"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_evictions{service!~\"tx-blaster.*\",service=~\"$srvc\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,instance) > 0 / 60",
     "legendFormat": "Cache evictions - {{container}} - {{instance}}"
    },
    {
     "expr": "sum(rate(teranode_blockvalidation_tx_meta_cache_get_origin{service!~\"tx-blaster.*\",service=~\"$srvc\",subsystem=~\"$subsystem\"}[$grouping_interval])) by (container,instance) > 0 / 60",
     "legendFormat": "Get from Aeropsike - {{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Tx Meta Cache Size in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_meta_cache_size{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container,instance)\n",
     "legendFormat": "Cache size - {{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Queued Subtrees in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_subtree_exists_cache{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container)",
     "legendFormat": "Subtrees queued - {{container}}"
    }
   ]
  },
  {
   "title": "Tx Meta Cache Number of Elements Added In Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_tx_meta_cache_total_elements_added{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"})by (container,instance)",
     "legendFormat": "Cache size - {{container}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Asset Service - HTTP Get Subtrees",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(rate(teranode_asset_http_get_subtree{namespace=~\"$namespace\"}[$grouping_interval])) by (app,)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Queued Blocks in Block Validation",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(teranode_blockvalidation_block_found_ch{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container)",
     "legendFormat": "Blocks queued - {{container}}"
    },
    {
     "expr": "sum(teranode_blockvalidation_last_validated_blocks_cache{service!~\"tx-blaster.*\",service=~\"$srvc\",service!~\"tx-blaster.*\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}) by (container)",
     "legendFormat": "Blocks in RAM - {{container}}"
    }
   ]
  },
  {
   "title": "TX Blaster Errors",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(increase(teranode_tx_blaster_errors{service=~\"$service\",namespace=~\"$namespace\",subsystem=~\"$subsystem\"}[$grouping_interval])) /60",
     "legendFormat": "Get"
    }
   ]
  }
 ]
}